apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P1809F7CD0C757532
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: grafana_org
      defaultBucket: grafana_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
